name:                push-swap
version:             0.1.0.0
github:              "githubuser/push-swap"
license:             BSD3
author:              "Emily Martins"
maintainer:          "example@example.com"
copyright:           "2019 Emily Martins"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/push-swap#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  push-swap-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - push-swap

tests:
  push-swap-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - push-swap
